version: '2.0'
displayName: '冷亭雨FlutteriOS'
stages:
  - build

build:
  stage: build
  image: macos-latest
  steps:
    - name: main
      script: |
        export PUB_HOSTED_URL=https://pub.flutter-io.cn
        export FLUTTER_STORAGE_BASE_URL=https://storage.flutter-io.cn
        git clone -b 3.24.0 --depth 1 https://github.com/flutter/flutter.git $HOME/flutter
        export PATH="$PATH:$HOME/flutter/bin"
        flutter pub get
        cd ios && pod install; cd ..
        flutter build ipa --no-codesign
        ls build/ios/ipa/
  artifacts:
    paths:
      - build/ios/ipa/*.ipa
    expire_in: 30 days